### ISSUE TITLE
RF 53 | Crear una evaluación genérica

### ISSUE THREAD

**Issue by ricardo020202** [Black-Dot-2024/cr-blackdot#116]
## Descripción
Como cliente de CR quiero ser capaz de crear y subir alguna evaluación genérica.

## Task
- [ ] El sistema permite al administrador crear una evaluación genérica.
- [ ] El sistema permite configurar información general de la evaluación (título, descripción, fechas, estado, mensaje de bienvenida).
- [ ] El sistema permite crear preguntas y asignarlas a esta evaluación.
- [ ] El sistema permite asignar a determinados colaboradores a la encuesta.
- [ ] El sistema registra una nueva instancia de una evaluación genérica.

## Estimación
- L - 8
