### ISSUE TITLE
RF17 Correo para evaluaciones

### ISSUE THREAD

**Issue by dvegaa20** [Black-Dot-2024/cr-blackdot#117]
## Descripción
Como cliente de CR quiero poder enviar las encuestas por medio de correo hacia los encuestados

## Task
- [ ] El sistema permite el envío por correo de una encuesta a varios usuarios
- [ ] El sistema personaliza el contenido del correo dependiendo del tipo de encuesta
- [ ] El sistema muestra en el correo la fecha inicio y final de la evaluación

## Tamaño
- S - 4
