### ISSUE TITLE
RF31 | Registrar avance de objetivos de desempeño

### ISSUE THREAD

**Issue by Riosmena** [Black-Dot-2024/cr-blackdot#118]
## Descripción
Como colaborador quiero registrar el avance de mis objetivos para analizar mi desempeño

## Task
- [ ] El sistema muestra el objetivo correspondiente
- [ ] El sistema muestra el espacio para ingresar el avance del objetivo
- [ ] El sistema registra el avance del objetivo
- [ ] El sistema actualiza el progreso del objetivo

## Extras
- M - 9
