### ISSUE TITLE
RF 46 | Filtrar reportes clima.

### ISSUE THREAD

**Issue by DanielSebasCM** [Black-Dot-2024/cr-blackdot#119]
## Descripción
Como cliente de CR quiero poder filtrar los reportes por área/departamento/dirección, etc.

## Task
- [x] El sistema muestra un popup para configurar los filtros de un reporte
- [x] Los filtros permiten agregar múltiples categorías.
- [x] Los filtros pueden incluir varios datos por categoría.
- [x] Se sistema debe mostrar un botón para reporte genérico (sin filtros) y otro para personalizado (Que salga el popup de filtros)

## Estimación
- XL - 8
