### ISSUE TITLE
RF 47 | Filtrar reportes NOM.

### ISSUE THREAD

**Issue by DanielSebasCM** [Black-Dot-2024/cr-blackdot#120]
## Descripción
Como cliente de CR quiero poder filtrar los reportes por área/departamento/dirección, etc.

## Task
- [ ] El sistema muestra un popup para configurar los filtros de un reporte
- [ ] Los filtros permiten agregar múltiples categorías.
- [ ] Los filtros pueden incluir varios datos por categoría.
- [ ] Se sistema debe mostrar un botón para reporte genérico (sin filtros) y otro para personalizado (Que salga el popup de filtros)
- [ ] El sistema muestra en los reportes que filtros se seleccionaron

## Estimación
- M - 3
