### ISSUE TITLE
RF52 | Subir catálogo de preguntas clima

### ISSUE THREAD

**Issue by UriGOPAR** [Black-Dot-2024/cr-blackdot#155]
## Descripción
Como cliente de CR quiero ser capaz de subir mis propias preguntas para la evaluación del clima.

## Task
- [ ] El sistema permite agregar de forma masiva un lote de preguntas clima.
- [ ] El sistema permite agregar una pregunta nueva a una evaluación.
- [ ] El sistema permite eliminar una pregunta a la vez.
- [ ] El sistema válida que las preguntas subidas contengan los campos necesarios para ser procesadas.

## Estimación
- M - 9
