### ISSUE TITLE
RF 56 | Agregar datos demográficos

### ISSUE THREAD

**Issue by DanielSebasCM** [Black-Dot-2024/cr-blackdot#173]
## Descripción
Como cliente de CR quiero agregar datos demográficos a mis empleados y que esto se refleje en los reportes

## Task
- [ ] El sistema precarga nuevos atributos de empleados. Ejm: Jefatura, Fecha de ingreso, etc.
- [ ] La plantilla y carga de usuarios externos debe de expandirse para cargar los atributos creados dinámicamente
- [ ] El sistema muestra estos datos demográficos en los reportes.
- [ ] El sistema permite filtrar por estos nuevos atributos.
- [ ] Los atributos que no tengan datos serán omitidos (si todos son N/A que no se muestren)

## Estimación
- XL - 8
