### ISSUE TITLE
RF 55 | Aceptar avance en objetivos

### ISSUE THREAD

**Issue by Riosmena** [Black-Dot-2024/cr-blackdot#177]
## Descripción

Como cliente de CR quiero evaluar, aceptar o rechazar y retroalimentar sobre el avance que han registrado mis colaboradores en sus objetivos.

## Task
- [ ] El sistema permite dejar retroalimentación a los colaboradores por avance dentro de los objetivos
- [ ] El sistema permite aceptar o declinar el avance registrado por los colaboradores en sus objetivos
- [ ] El sistema permite retroalimentar al colaborador sobre el avance en sus objetivos
- [ ] El sistema no registra el avance si el mismo fue declinado por el cliente de CR

## Extras
- XL - 8
