### ISSUE TITLE
RF 58 | Mostrar plan de acción

### ISSUE THREAD

**Issue by Bromaeg** [Black-Dot-2024/cr-blackdot#178]
## Descripción
Como Cliente de CR quiero que se visualice el plan de acción generado 

## Task
- [x] El sistema muestra un botón el cual permite generar el plan de acción
- [x] El sistema permite visualizar el plan de acción generado en un formato claro y estructurado dentro del reporte.
- [x] El sistema permite editar el plan de acción que fue generado por la IA
- [ ] La visualización del plan de acción se puede ver en los navegadores de Mozilla, Chrome, Edge y Safari a su última versión estable, según Odoo.
- [x] La visualización del plan de acción es responsiva.

## Extras
- M - 3
