### ISSUE TITLE
RF 27 | Modificación de los resultados de evaluación

### ISSUE THREAD

**Issue by VON0222** [Black-Dot-2024/cr-blackdot#179]
## Descripción
Como cliente de CR quiero modificar los resultados de evaluación para tener flexibilidad con respecto a factores externos que pudieran alterar los resultados de evaluación.

## Task
- [ ] El sistema muestra la opción de editar los resultados de una evaluación.
- [ ] El sistema permite modificar los resultados de una evaluación.
- [ ] El sistema registra el cambio en los resultados de una evaluación.
- [ ] El sistema muestra el cambio en los resultados de una evaluación.

## Estimación
- M - 3
