### ISSUE TITLE
RF35 | Asignación de evaluaciones 360°

### ISSUE THREAD

**Issue by UriGOPAR** [Black-Dot-2024/cr-blackdot#26]
## Descripción
Como cliente de CR quiero asignar evaluaciones 360° a colaboradores de acuerdo al tipo de evaluación 360°

## Task
- [ ] El sistema permite elegir el tipo de evaluación (90, 180, 270, 360, autoevaluación).
- [ ] El sistema muestra la opción de asignar colaboradores de acuerdo al tipo de evaluación.
- [ ] El sistema muestra los colaboradores asignados para que realicen la evaluación.
- [ ] El sistema muestra la opción de quitar colaboradores para la evaluación.
- [ ] El sistema muestra la opción de enviar la evaluación.

## Estimación
- L-8
