### ISSUE TITLE
RF40 | Responder mis evaluaciones asignadas NOM 035

### ISSUE THREAD

**Issue by UriGOPAR** [Black-Dot-2024/cr-blackdot#29]
## Descripción
Como colaborador de la empresa cliente de CR quiero responder mis evaluaciones asignadas para evaluar competencias específicas.

## Task
- [x] El sistema únicamente permitirá contestar la evaluación mientras el estado de la misma sea "Abierto".
- [x] El sistema permite contestar las preguntas de la evaluación.
- [x] El sistema registra las respuestas de la evaluación realizada.
- [x] El sistema no permite cambiar las respuestas si la evaluación ya fue enviada.

## Estimación
- L - 5
