### ISSUE TITLE
RF38 | Exportar reporte NOM035 y CLIMA

### ISSUE THREAD

**Issue by UriGOPAR** [Black-Dot-2024/cr-blackdot#30]
## Descripción
Como Cliente de CR quiero exportar los reportes de una evaluación de tipo NOM035 o de CLIMA, para acceder más fácilmente a los resultados.

## Task
- [ ] El sistema muestra los resultados de la evaluación actual.
- [ ] El sistema permite elegir que elementos exportar de los resultados de la evaluación.
- [ ] El sistema da la opción de exportar el reporte.
- [ ] El sistema descarga el reporte de evaluación

## Estimación
- S-2
