### ISSUE TITLE
RF36 | Consultar colaboradores con objetivos de desempeño

### ISSUE THREAD

**Issue by UriGOPAR** [Black-Dot-2024/cr-blackdot#32]
## Descripción
Como cliente de CR quiero consultar los colaboradores que tienen objetivos de desempeño para monitorear su avance.

## Task
- [ ] El sistema muestra una lista de los colaboradores con objetivos.
- [ ] El sistema permite visualizar los objetivos de cada colaborador.
- [ ] El sistema permite visualizar los detalles (título, descripción, unidad de medida, piso mínimo y máximo, y peso) de cada objetivo

## Estimación
- S-2
