### ISSUE TITLE
Creación de evaluacion 035

### ISSUE THREAD

**Issue by Bromaeg** [Black-Dot-2024/cr-blackdot#4]
## Descripción
Como administrador quiero crear la evaluación NOM 035 para que los clientes de CR evalúen a sus colaboradores

## Task
- [ ] El sistema permite al administrador crear una evaluación basada en la  NOM 035.
- [ ] El sistema muestra las preguntas de evaluación de la NOM 035 cargadas previamente.
- [ ] El sistema muestra una vista previa de la evaluación tipo NOM 035
- [ ] El sistema permite elegir el tipo de escala de las respuestas 
- [ ] El sistema registra una nueva instancia de una evaluación tipo NOM 035

## Estimacion
- S - 6
