### ISSUE TITLE
RF45 | Asignar a usuarios no registrados

### ISSUE THREAD

**Issue by UriGOPAR** [Black-Dot-2024/cr-blackdot#96]
## Descripción
El sistema permite enviar la evaluación a sistema no registrados en Odoo

## Task
- [x] Cargar csv
- [x] Asociar usuarios externos a evaluación
- [x] Generar token y enviar correo
- [x] Validar que estén todas las columnas
- [x] Validar que los datos sean correctos
- [x] Cargar datos de usuarios externos para las gráficas de demográficos

## Extras
- M - 8
